#!/bin/bash

# determine screen res
RES=`xdpyinfo | grep dimensions`

# 1440?
if [[ $RES =~ 2560x1440 ]]; then
	RES=1440
else
	RES=1080
fi

# i3lock not already running?
if [ ! $(ps -ef | grep -E "(i3|sway)lock" | grep -v lock) ]; then
	if [[ ! $(pidof sway) ]]; then
		~/Downloads/i3lock-lixxia/i3lock -l '#ffffff' -i /home/raidzero/wallpapers/trust_the_computer-$RES.png -e
	else
		swaylock -i /home/raidzero/wallpapers/trust_the_computer-$RES.png
	fi
fi
