#! /bin/sh
# if 4k, start everything in floating mode
[[ $(xdpyinfo | grep -i 3840x2160) ]] && bspc rule -a "*" state=floating follow=on

sxhkd &

bspc config focus_follows_pointer true
bspc config click_to_focus true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio				0.52
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config single_monocle			true

sh ~/.config/i3/autostart.sh &
